name: Коменнтатотр

on:
  push:
    branches:
      - '**'  # Это указывает на все ветки

jobs:
  post-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get commit message
      id: get_commit
      run: echo "::set-output name=message::$(git log -1 --pretty=format:'%s')"

    - name: Post comment
      uses: peter-evans/commit-comment@v1
      with:
        token: ${{ secrets.TOKEN }}
        body: "
          Это тестовый пуск комментария на появления коммита.
          Commit message: ${{ steps.get_commit.outputs.message }}"